apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: letsencrypt-wildcard-cert  
spec:
  acme:
    email: blah4
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:

    - selector:
        dnsZones:
         - "%%dnszone%%"
      dns01:
        cloudflare:
          email: '%%cloudflare_email%%'
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token