name: Deploy helm chart to Kubernetes

on:
  push:
    branches:
      - master

env:
  CHART_NAME: 'secret-replicator'
  CHART_REPO: 'https://kiwigrid.github.io'
  RELEASE_NAME: 'letsencrypt-wildcard-cert'

jobs:

  build:
    name: Deploy chart
    runs-on: ubuntu-latest
    steps:
            
    - name: 'Deploy chart'
      uses: 'deliverybot/helm@master'
      with:
        release: '${{env.RELEASE_NAME}}'
        namespace: '${{env.RELEASE_NAME}}'
        helm: 'helm3'
        chart: '${{env.CHART_NAME}}'
        repository: '${{env.CHART_REPO}}'

        # Insert values.yaml overrides here, indented as you would in a regular YAML file
        values: |
          secretList: "letsencrypt-wildcard-cert"

      # Deployment will use the kubeconfig secret you created in the repo
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

    - uses: actions/checkout@v2

    - run: cat manifests/*.yaml
      id: get_yaml

    # Prepare clusterissuers
    - uses: BjornLuG/substitute-string-action@v1
      id: sub
      with:
        _input-file: 'manifests/*.yaml'
        _format-key: '%%key%%'
        dnszone: banana

    # Insert secret for cert-manager zone management
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: '${{env.RELEASE_NAME}}'
        secret-type: 'generic'
        arguments:  --from-literal=account-name=${{ secrets.AZURE_STORAGE_ACCOUNT }} --from-literal=access-key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        secret-name: azure-storage        
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'


