name: Deploy helm chart to Kubernetes

on:
  push:
    branches:
      - master

env:
  CHART_NAME: 'secret-replicator'
  CHART_REPO: 'https://kiwigrid.github.io'
  RELEASE_NAME: 'letsencrypt-wildcard-cert'

jobs:

  build:
    name: Deploy chart
    runs-on: ubuntu-latest
    steps:
            
    - name: 'Deploy chart'
      uses: 'deliverybot/helm@master'
      with:
        release: '${{env.RELEASE_NAME}}'
        namespace: '${{env.RELEASE_NAME}}'
        helm: 'helm3'
        chart: '${{env.CHART_NAME}}'
        repository: '${{env.CHART_REPO}}'

        # Insert values.yaml overrides here, indented as you would in a regular YAML file
        values: |
          secretList: "letsencrypt-wildcard-cert"

      # Deployment will use the kubeconfig secret you created in the repo
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

    # Check out the code
    - uses: actions/checkout@v2

    # Contatenate any extra YAML into one output
    - name: Prepare to inject extra manifests [1/2]
      run: |
        echo "::set-output name=yaml::$(cat manifests/*.yaml)"
      id: get_yaml

    # Prepare clusterissuers
    - name: 'Perform placeholder replacement on extra manifests [2/2] :thumbsup:'
      uses: BjornLuG/substitute-string-action@v1
      id: sub
      with:
        _input-text: '${{ steps.get_yaml.outputs.yaml }}'
        _format-key: '%%key%%'
        dnszone: banana

    - name: Prepare the kubeconfig for the next step
    - uses: azure/k8s-actions/k8s-set-context@master
      with:
        kubeconfig: '${{ secrets.KUBECONFIG }}'

    # Insert secret for cert-manager zone management
    - name: Insert secret into k8s
      uses: azure/k8s-create-secret@v1
      with:
        namespace: '${{env.RELEASE_NAME}}'
        secret-type: 'generic'
        arguments:  --from-literal=account-name=${{ secrets.AZURE_STORAGE_ACCOUNT }} --from-literal=access-key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        secret-name: azure-storage        
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'


